[theme]
primaryColor = "#FF69B4"        # Changes your submit buttons and highlights to vibrant pink
backgroundColor = "#C71585"              #"#FFFFFF"
secondaryBackgroundColor = "#FFF0F5" # Makes form backgrounds a soft blush pink
textColor = "#31333E"

